kind: pipeline
name: push-master
steps:
  - name: build-test
    image: node:alpine
    commands:
      - npm install
      - npm run test
      - npm run build
    when:
      branch: master
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
    when:
      branch: master
