kind: pipeline
name: push-master
steps:
  - name: install-dependencies
    image: node:alpine
    commands:
      - npm install
    when:
      branch: master
  - name: test
    image: node:alpine
    commands:
      - npm run test
    when:
      branch: master
  - name: build
    image: node:alpine
    commands:
      - npm run build
    when:
      branch: master
  - name: code-coverage
    image: node:alpine
    commands:
      - npm run report-coverage
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    when:
      branch: master
