kind: pipeline
name: push-master
steps:
  - name: install-dependencies
    image: node:alpine
    commands:
      - npm install
    when:
      branch: master
  - name: test
    image: node:alpine
    commands:
      - npm run test
    when:
      branch: master
  - name: build
    image: node:alpine
    commands:
      - npm run build
    when:
      branch: master
  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: CODECOV_TOKEN
    when:
      branch: master
